### ISSUE TITLE
Logger memory leak 

### ISSUE THREAD

**Issue by slack** [deis/logger#104]
Looks like logger may be leaking a couple MiB/hr

![2016-08-25 at 09 46](https://cloud.githubusercontent.com/assets/28873/17971430/d6f8bd4a-6aa8-11e6-87da-4a9de14c0347.png)

**Comment by rimusz** [comment]
yes, I'm seeing the same, also logger time by time uses a lot of cpu too

**Comment by jchauncey** [comment]
I think this is related to - https://github.com/deis/logger/issues/102

**Comment by jchauncey** [comment]
So there were issues in the memory graphs for certain components that I have PR'd. Here is what my graph shows for the last 12 hours - 
<img width="1409" alt="screen shot 2016-08-25 at 12 51 54 pm" src="https://cloud.githubusercontent.com/assets/430360/17978180/d10548a8-6ac2-11e6-8309-67d1f497a07c.png">

**Comment by jchauncey** [comment]
added pprof in #108 to help debug this

**Comment by mboersma** [comment]
We think this is fixed by #113--let's verify that once it merges.
