### ISSUE TITLE
Message with newlines in them get cut off in deis logs

### ISSUE THREAD

**Issue by helgi** [deis/logger#109]
`(app::deploy): There was a problem deploying v6. Rolling back process types to release v5.\nThere was a problem while deploying v6 of unbent-larkspur-cmd. Additional information:\nError: image deis/example-foo:latest not found`

This only shows up to the first `\n` in `deis logs`

**Comment by jchauncey** [comment]
We should get the last \n and split on that

**Comment by jchauncey** [comment]
closed in https://github.com/deis/controller/issues/1027
