### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by felipejfc** [deis/logger#114]
I think this component needs better documentation, for example, I have some doubts here, how many of the last log lines will redis keep for each app (or process per app, don't know...)? Also, I have the feeling that the logs are not being streamed in "realtime", some times I want to see the log of an app and the log lines I expected to see are not there yet when I issue `deis logs -a xxx`, do we have a buffer that needs to be filled before the messages are sent to redis?

If this kind of details is documented somewhere I have not found it...

regards

**Comment by jchauncey** [comment]
@felipejfc checkout #115
