### ISSUE TITLE
Deis with Loggly

### ISSUE THREAD

**Issue by deis-admin** [deis/logger#133]
_From @gergelyke on December 28, 2015 8:26_

To be able to work with Loggly, I need to set a syslog header (https://www.loggly.com/docs/streaming-syslog-without-using-files/)

Is there a way to set it in Deis?

_Copied from original issue: deis/deis#4814_

**Comment by deis-admin** [comment]
_From @geeksoul-me on December 29, 2015 10:29_

I too need info on this.

**Comment by deis-admin** [comment]
_From @krancour on January 4, 2016 21:51_

> Is there a way to set it in Deis?

Not currently.  Feel free to take a stab at adding support for this to the logger.

**Comment by deis-admin** [comment]
_From @bacongobbler on June 9, 2016 21:47_

PRs this-a-way (for Workflow, the successor to Deis) --> https://github.com/deis/logger

**Comment by deis-admin** [comment]
_From @bacongobbler on November 23, 2016 21:0_

Loggly has support for fluentd as well, which you can contribute a PR to deis/fluentd.

https://www.loggly.com/docs/fluentd-logs/

**Comment by krancour** [comment]
@jchauncey is their currently adequate support for custom fluentd plugins that this could be closed without actually implementing a new feature?

**Comment by jchauncey** [comment]
Yes. The documentation should be adequate enough to show how to do it that we can close this.
