### ISSUE TITLE
Logger does not support an off-cluster Redis in Cluster mode

### ISSUE THREAD

**Issue by mariusmarais** [deis/logger#143]
Deploying Workflow with an off-cluster Redis configuration, where Redis itself is running in cluster mode, does not work.

Symptoms include `deis logs` working immediately after deploying a new app, but not again after some time.  Viewing the `deis-logger-xxx` pod's logs show 100s of:
```
2017-06-08T10:00:04.75420277Z 2017/06/08 10:00:04 Error executing pipeline: MOVED 2589 172.20.0.39:6379
```

The `MOVED` error means the client needs to reissue the request to the named IP as per the [Redis docs](https://redis.io/topics/cluster-spec).

Please update documentation that Redis Cluster is not supported in the short term and investigate implementation of cluster mode in the longer term.

(FWIW: It's quite easy to boot up a Redis Cluster using AWS ElastiCache.)

**Comment by jchauncey** [comment]
Cc @krancour

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/logger#1
