### ISSUE TITLE
Remove unecessary type assertions

### ISSUE THREAD

**Issue by krancour** [deis/logger#33]
Example: https://github.com/deis/logger/blob/master/syslogish/server.go#L129

These aren't needed.  They probably were needed at a moment in time and then weren't as the code evolved.  They can go.

**Comment by arschles** [comment]
Most type assertions will be removed when @jchauncey finishes changing architecture according to #84. His working branch is at https://github.com/jchauncey/logger/tree/use-nsq

**Comment by Joshua-Anderson** [comment]
nsq work has now been merged. @jchauncey is this still an issue?

**Comment by krancour** [comment]
The refactor eliminated the code in question.
