### ISSUE TITLE
Type assertions need checking

### ISSUE THREAD

**Issue by krancour** [deis/logger#34]
These are several cases of values being coerced to strings here.  They may require checking.

https://github.com/deis/logger/blob/master/syslogish/server.go#L132-L142

**Comment by arschles** [comment]
Most type assertions will be removed when @jchauncey finishes changing architecture according to #84. His working branch is at https://github.com/jchauncey/logger/tree/use-nsq

**Comment by jchauncey** [comment]
closing as this is no longer necessary
