### ISSUE TITLE
Installing deis logger error

### ISSUE THREAD

**Issue by ozanyurt** [deis/logger#49]
When I try to install deis-logger I am getting this output:

---> Running `kubectl create -f` ...
serviceaccount "deis-logger-fluentd" created

serviceaccount "deis-logger" created

service "deis-logger" created

replicationcontroller "deis-logger" created

The DaemonSet "deis-logger-fluentd" is invalid.
spec.selector: Invalid value: {}: empty selector is not valid for daemonset.

[ERROR] Failed to upload manifests: exit status 1

> kubectl get pods --namespace=deis 

deis-builder-u48e2            1/1       Running   8          22h
deis-controller-tejy0         1/1       Running   8          22h
deis-database-ut9ml           1/1       Running   0          22h
deis-logger-ne71x             1/1       Running   0          2m
deis-minio-r8idc              1/1       Running   0          22h
deis-registry-i5bi2           1/1       Running   10         22h
deis-router-zn9h6             1/1       Running   0          22h
deis-workflow-manager-irxiw   1/1       Running   0          15m

Additional info:

> kubectl version

Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8", GitCommit:"a8af33dc07ee08defa2d503f81e7deea32dd1d3b", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.1", GitCommit:"50809107cd47a1f62da362bccefdd9e6f7076145", GitTreeState:"clean"}

> [vagrant@kubernetes-master ~]$ curl -s http://127.0.0.1:8080/apis/extensions/v1beta1

{
  "kind": "APIResourceList",
  "groupVersion": "extensions/v1beta1",
  "resources": [
    {
      "name": "daemonsets",
      "namespaced": true,
      "kind": "DaemonSet"
    },
    {
      "name": "daemonsets/status",
      "namespaced": true,
      "kind": "DaemonSet"
    },
    {
      "name": "deployments",
      "namespaced": true,
      "kind": "Deployment"
    },
    {
      "name": "deployments/rollback",
      "namespaced": true,
      "kind": "DeploymentRollback"
    },
    {
      "name": "deployments/scale",
      "namespaced": true,
      "kind": "Scale"
    },
    {
      "name": "deployments/status",
      "namespaced": true,
      "kind": "Deployment"
    },
    {
      "name": "horizontalpodautoscalers",
      "namespaced": true,
      "kind": "HorizontalPodAutoscaler"
    },
    {
      "name": "horizontalpodautoscalers/status",
      "namespaced": true,
      "kind": "HorizontalPodAutoscaler"
    },
    {
      "name": "ingresses",
      "namespaced": true,
      "kind": "Ingress"
    },
    {
      "name": "ingresses/status",
      "namespaced": true,
      "kind": "Ingress"
    },
    {
      "name": "jobs",
      "namespaced": true,
      "kind": "Job"
    },
    {
      "name": "jobs/status",
      "namespaced": true,
      "kind": "Job"
    },
    {
      "name": "replicasets",
      "namespaced": true,
      "kind": "ReplicaSet"
    },
    {
      "name": "replicasets/scale",
      "namespaced": true,
      "kind": "Scale"
    },
    {
      "name": "replicasets/status",
      "namespaced": true,
      "kind": "ReplicaSet"
    },
    {
      "name": "replicationcontrollers",
      "namespaced": true,
      "kind": "ReplicationControllerDummy"
    },
    {
      "name": "replicationcontrollers/scale",
      "namespaced": true,
      "kind": "Scale"
    }
  ]
}

**Comment by sgoings** [comment]
@jchauncey any thoughts?

**Comment by jchauncey** [comment]
Interesting. I haven't had a 1.2 cluster to test against so they may have changed something. I'll get on this ASAP.

**Comment by jchauncey** [comment]
So I have been successfully installing logger on a 1.2 cluster (with no changes). Have you tried to reinstalling the component since receiving this error?

**Comment by ozanyurt** [comment]
Yes, but I am new to all of this. Can you give me some path for reinstalling process. Thanks

**Comment by ozanyurt** [comment]
I finally installed successfully. First I remove all from  cluster with `make kube-delete` and I run `make kube-install `.

I think problem was `helm install deis/deis-logger` command. I will try again later but now everything seems to work for me.
