### ISSUE TITLE
Timestamp all log entries

### ISSUE THREAD

**Issue by jchauncey** [deis/logger#71]
It is extremely useful to capture the timestamp for display purposes in `deis logs`. To do this we will need to make sure the following things are done:

* Right now we throw away the timestamp we get from fluentd so we will need to make sure that we add that to the json that is sent to logger.
* In logger when we go to store the message in redis we should prepend the timestamp we got from fluentd at the beginning of the message.
* Once we have the timestamp being return to the CLI we will need to have it skip the timestamp part of the message for colorizing purposes.

**Comment by jchauncey** [comment]
moved to rc1

**Comment by bacongobbler** [comment]
which log entries still require timestamps? Just application logs? :)

**Comment by jchauncey** [comment]
yeah i think so.

**Comment by mboersma** [comment]
@jchauncey is this going in to v2.0-rc1?

**Comment by jchauncey** [comment]
no

**Comment by bacongobbler** [comment]
is this resolved via #123?

**Comment by jchauncey** [comment]
Yes
