### ISSUE TITLE
update logger docs to include how to modify running fluentdpods

### ISSUE THREAD

**Issue by jchauncey** [deis/logger#74]
http://docs-v2.readthedocs.io/en/v2.0.0-beta2/managing-workflow/platform-logging/

Should show how to modify fluentd so that you can add papertrail

**Comment by vdice** [comment]
ping @jchauncey as to if this is still scheduled for the `v2.0-rc1` milestone

**Comment by bacongobbler** [comment]
https://deis.com/docs/workflow/managing-workflow/tuning-component-settings/#customizing-fluentd
