### ISSUE TITLE
upgrading logger component makes previous version logs unavailable 

### ISSUE THREAD

**Issue by smothiki** [deis/logger#86]
This is an existing behavior in logger, logs are not persistent. If we update the logger the logs from the previous logger version are not available.  

Just opening this issue to keep track of this behavior

**Comment by mboersma** [comment]
Maybe we could figure out and document a way to save and restore the logger data during a [Workflow upgrade](http://docs-v2.readthedocs.io/en/latest/managing-workflow/upgrading-workflow/)? Although that doesn't address the general problem: loss of data if a logger pod exits.

**Comment by jchauncey** [comment]
We now back logger by redis so this isnt a problem
